name: fun_refresh # 项目名
description: 趣刷 # 描述
version: 1.0.9 # 当前版本号: 主.次.修(alphaNo.->betaNo.->rcNo.->stableNo.)

environment: # 语言环境
  sdk: ">=2.7.0 <3.0.0"

dependencies: # 拓展插件集合 https://pub.dev
  flutter:  # 开发工具
    sdk: flutter 
  flutter_localizations: # 国际化
    sdk: flutter
  url_launcher:  # 跳转至浏览器
  flutter_svg:  # 矢量图加载
  dio:  # 网络请求
  webview_flutter:  # 原生网页浏览
  shared_preferences:  # 偏好设置
  video_player:  # 原生视频播放
  path:  # 多平台路径操作库
  json_annotation:  # 简谱序列化注解
  flutter_staggered_grid_view:  # 瀑布流网格
  flame:  # 游戏引擎
  toast:  # 吐司字幕
  flutter_bloc:  # 业务逻辑组件模式
  flare_flutter:  # 2D闪光动画
  overlay_support:  # 全局覆盖通知
  soundpool:  # 音效池
  vibration:  # 震动器
  flutter_colorpicker:  # 颜色选择器
  cached_network_image:  # 网络图片加载
  sensors:  # 传感器
  permission_handler:  # 获取权限
  connectivity:  # 网络状态监听
  photo_view:  # 图片浏览
  rxdart:  # 异步Dart
  audioplayers:  # 音频播放
  flutter_speed_dial:  # 动画悬浮按钮
  camera:  # 相机

dev_dependencies: # 调试插件集合
  flutter_test: # 自动化测试
    sdk: flutter
  build_runner:  # 代码生成器
  built_value_generator:  # 生成字段
  json_serializable:  # 简谱序列化标签注解
  
flutter:  # 资源配置集合
  uses-material-design: true  # 激活材料设计
  assets:
    - assets/svg/ # 图标

    # 图片
    - assets/images/ 
    - assets/images/src/
    - assets/images/flappy_bird/
    - assets/images/reward_wheel/
    - assets/images/tetris/
    
    - assets/images/bejeweled/
    - assets/images/bejeweled/bombs/
    - assets/images/bejeweled/borders/
    - assets/images/bejeweled/deco/
    - assets/images/bejeweled/tiles/

    # 动画
    - assets/animations/

    # 音效
    - assets/audio/
    - assets/audio/bejeweled/
    - assets/audio/tetris/
    - assets/audio/flappy_bird/
    - assets/audio/dino_run/
    
    # 简谱
    - assets/json/
    - assets/json/config/

  fonts:
    - family: StarJedi
      fonts:
        - asset: assets/fonts/starjedi.ttf
        